# Consul
consul_domain := $(shell hostname -f)
consul_data_center := consul
consul_virtual_host := $(consul_data_center).$(consul_domain)
consul_virtual_port := 8500
consul_advertise_ip := $(shell sudo ifconfig eth0 | grep -oP 'inet addr:\K\S+')
dns_search := "service.$(consul_data_center).$(consul_domain)"
server_dns := $(shell grep -i nameserver /etc/resolv.conf|head -n1|cut -d ' ' -f2)
container_dns := 172.17.0.1
